spring:
  application:
    name: saju-taro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sajutaro

    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080